parameters:
  env(AUXMONEY_OPENTRACING_AGENT_PORT): '6831'
  env(AUXMONEY_OPENTRACING_SAMPLER_CLASS): Jaeger\Sampler\ConstSampler
  env(AUXMONEY_OPENTRACING_SAMPLER_VALUE): 'true'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Auxmoney\OpentracingBundle\Factory\JaegerConfigFactory:
    class: Auxmoney\OpentracingBundle\Factory\JaegerStaticConfigFactory

  Auxmoney\OpentracingBundle\Factory\TracerFactory:
    class: Auxmoney\OpentracingBundle\Factory\JaegerTracerFactory
